#!/bin/sh
set -e

VERSION="1.0.2"

case "$1" in
    configure)
        dkms add -m agnocast -v "$VERSION"
        dkms build -m agnocast -v "$VERSION"
        dkms install -m agnocast -v "$VERSION"
    ;;
esac

#DEBHELPER#

exit 0
